<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            ['type' => 1, 'parent' => NULL, 'code' => '120006', 'name' => 'Akumulasi Depresiasi Aset Tetap', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 1, 'parent' => 7, 'code' => '12000601', 'name' => 'Akumulasi Penyusutan Gedung', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 1, 'parent' => 7, 'code' => '12000604', 'name' => 'Akumulasi Penyusutan Inventaris Kantor', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 1, 'parent' => 7, 'code' => '12000602', 'name' => 'Akumulasi Penyusutan Kendaraan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 1, 'parent' => 7, 'code' => '12000603', 'name' => 'Akumulasi Penyusutan Peralatan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 2, 'parent' => NULL, 'code' => '1105', 'name' => 'Aset Lancar Lainnya', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 2, 'parent' => 5, 'code' => '110501', 'name' => 'Perlengkapan Kantor', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 2, 'parent' => 5, 'code' => '110502', 'name' => 'Sewa Gedung Dibayar Dimuka', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 2, 'parent' => 5, 'code' => '110503', 'name' => 'Asuransi Dibayar Dimuka', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 2, 'parent' => 5, 'code' => '110504', 'name' => 'PPN Masukan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 2, 'parent' => 5, 'code' => '110505', 'name' => 'PPh 23 Penjualan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 3, 'parent' => NULL, 'code' => '1200', 'name' => 'Aset Tetap', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 3, 'parent' => 6, 'code' => '120001', 'name' => 'Tanah', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 3, 'parent' => 6, 'code' => '120002', 'name' => 'Gedung', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 3, 'parent' => 6, 'code' => '120003', 'name' => 'Kendaraan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 3, 'parent' => 6, 'code' => '120004', 'name' => 'Peralatan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 3, 'parent' => 6, 'code' => '120005', 'name' => 'Inventaris Kantor', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => NULL, 'code' => '6000', 'name' => 'Beban Operasional', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600001', 'name' => 'Beban Iklan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600002', 'name' => 'Beban Komisi', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600003', 'name' => 'Beban Bensin, Parkir, dan Tol Kendaraan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600004', 'name' => 'Beban Gaji, Upah, dan Honorer', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600005', 'name' => 'Beban Bonus, Pesangon, dan Kompensasi', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600006', 'name' => 'Beban Transportasi Karyawan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600007', 'name' => 'Beban Katering dan Makan Karyawan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600008', 'name' => 'Beban Tunjangan Kesehatan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600009', 'name' => 'Beban Asuransi Karyawan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600010', 'name' => 'Beban THR', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600011', 'name' => 'Beban Listrik', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600012', 'name' => 'Beban PAM', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600013', 'name' => 'Beban Telekomunikasi', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600014', 'name' => 'Beban Ekspedisi, Pos dan Meterai', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600015', 'name' => 'Beban Perjalanan Dinas', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600016', 'name' => 'Beban Perlengkapan Kantor', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600017', 'name' => 'Beban Pajak Penghasilan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600018', 'name' => 'Beban Retribusi dan Sumbangan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600019', 'name' => 'Beban Sewa Gedung', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600020', 'name' => 'Beban Operasional Lainnya', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600021', 'name' => 'Beban Penyusutan Gedung', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600022', 'name' => 'Beban Penyusutan Kendaraan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600023', 'name' => 'Beban Penyusutan Peralatan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600024', 'name' => 'Beban Penyusutan Inventaris Kantor', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 6, 'parent' => 13, 'code' => '600025', 'name' => 'Beban Software', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => NULL, 'code' => '7200', 'name' => 'Beban Di Luar Usaha', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 15, 'code' => '720001', 'name' => 'Beban Bunga Pinjaman', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 15, 'code' => '720002', 'name' => 'Beban Administrasi Bank dan Buku Cek/Giro', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 15, 'code' => '720003', 'name' => 'Pajak Jasa Giro', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 15, 'code' => '720004', 'name' => 'Laba/Rugi Terealisasi', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 15, 'code' => '720005', 'name' => 'Laba/Rugi Belum Terealisasi', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 15, 'code' => '720006', 'name' => 'Laba/Rugi Disposisi Aset', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 15, 'code' => '720007', 'name' => 'Beban Di Luar Usaha Lainnya', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 16, 'code' => '7201', 'name' => 'Laba/Rugi Terealisasi', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 16, 'code' => '720101', 'name' => 'Laba/Rugi Terealisasi IDR', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 16, 'code' => '720102', 'name' => 'Laba/Rugi Terealisasi USD', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 17, 'code' => '7202', 'name' => 'Laba/Rugi Belum Terealisasi', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 17, 'code' => '720201', 'name' => 'Laba/Rugi Belum Terealisasi IDR', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 5, 'parent' => 17, 'code' => '720202', 'name' => 'Laba/Rugi Belum Terealisasi USD', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 7, 'parent' => NULL, 'code' => '5101', 'name' => 'Beban Pokok Penjualan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 12, 'parent' => NULL, 'code' => '2101', 'name' => 'Hutang Usaha', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 12, 'parent' => 7, 'code' => '210101', 'name' => 'Hutang Usaha IDR', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 12, 'parent' => 7, 'code' => '210102', 'name' => 'Uang Muka Penjualan IDR', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 12, 'parent' => 7, 'code' => '210103', 'name' => 'Hutang Usaha USD', 'currency' => 2, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 12, 'parent' => 7, 'code' => '210104', 'name' => 'Uang Muka Penjualan USD', 'currency' => 2, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 4, 'parent' => NULL, 'code' => '1101', 'name' => 'Kas dan Bank', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 4, 'parent' => 1, 'code' => '110101', 'name' => 'Kas Kecil', 'currency' => 1, 'initial_balance' => 11940924, 'effective_date' => '2021-02-14'],
            ['type' => 4, 'parent' => 1, 'code' => '110102', 'name' => 'Bank', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 4, 'parent' => 1, 'code' => '110103', 'name' => 'Kas Kecil Pamulang', 'currency' => 1, 'initial_balance' => 1000000, 'effective_date' => '2021-02-14'],
            ['type' => 4, 'parent' => 1, 'code' => '110104', 'name' => 'Kas Penerimaan/Pembayaran Tunai', 'currency' => 1, 'initial_balance' => 383825, 'effective_date' => '2021-02-14'],
            ['type' => 4, 'parent' => NULL, 'code' => '1102', 'name' => 'Setara Kas', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 4, 'parent' => 2, 'code' => '110201', 'name' => 'Deposito Bank', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 4, 'parent' => 2, 'code' => '110202', 'name' => 'Bank Mandiri a/c 156-001-413-1496', 'currency' => 1, 'initial_balance' => 6040486, 'effective_date' => '2021-02-14'],
            ['type' => 4, 'parent' => 2, 'code' => '110203', 'name' => 'Permata Syariah a/c 070-223-0551', 'currency' => 1, 'initial_balance' => 10168831, 'effective_date' => '2021-02-14'],
            ['type' => 4, 'parent' => 2, 'code' => '110204', 'name' => 'BCA a/c 521-120-7249', 'currency' => 1, 'initial_balance' => 6164433, 'effective_date' => '2021-02-14'],
            ['type' => 10, 'parent' => NULL, 'code' => '2201', 'name' => 'Hutang Jangka Panjang', 'currency' => 1, 'initial_balance' => 329217, 'effective_date' => '2021-02-14'],
            ['type' => 11, 'parent' => 9, 'code' => '220101', 'name' => 'PPN Keluaran', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 11, 'parent' => 9, 'code' => '220102', 'name' => 'PPh 23 Pembelian', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 11, 'parent' => 9, 'code' => '220103', 'name' => 'Hutang Pembelian Belum Ditagih', 'currency' => 1, 'initial_balance' => -4119880, 'effective_date' => '2021-02-14'],
            ['type' => 9, 'parent' => NULL, 'code' => '3000', 'name' => 'Modal', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 9, 'parent' => 10, 'code' => '300001', 'name' => 'Equitas Saldo Awal', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 9, 'parent' => 10, 'code' => '300002', 'name' => 'Laba Ditahan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 9, 'parent' => 10, 'code' => '300003', 'name' => 'Modal Saham', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 8, 'parent' => NULL, 'code' => '4000', 'name' => 'Pendapatan Operasional', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 8, 'parent' => 11, 'code' => '400001', 'name' => 'Penjualan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 8, 'parent' => 11, 'code' => '400002', 'name' => 'Pendapatan Jasa', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 8, 'parent' => 11, 'code' => '400003', 'name' => 'Retur Penjualan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 8, 'parent' => 11, 'code' => '400004', 'name' => 'Diskon Penjualan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 8, 'parent' => NULL, 'code' => '4401', 'name' => 'Diskon Penjualan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 8, 'parent' => 12, 'code' => '440101', 'name' => 'Diskon Penjualan IDR', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 8, 'parent' => 12, 'code' => '440102', 'name' => 'Diskon Penjualan USD', 'currency' => 2, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 13, 'parent' => NULL, 'code' => '7100', 'name' => 'Pendapatan Diluar Usaha', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 13, 'parent' => 14, 'code' => '710001', 'name' => 'Pendapatan Jasa Giro', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 13, 'parent' => 14, 'code' => '710002', 'name' => 'Pendapatan Bunga Deposito', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 13, 'parent' => 14, 'code' => '710003', 'name' => 'Penjualan Persediaan/Perlengkapan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 13, 'parent' => 14, 'code' => '710004', 'name' => 'Laba/Rugi Revaluasi Aset', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 13, 'parent' => 14, 'code' => '710005', 'name' => 'Pendapatan Diluar Usaha Lainnya', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 13, 'parent' => 14, 'code' => '710006', 'name' => 'Pendapatan Bunga/Bagi Hasil Tabungan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 14, 'parent' => NULL, 'code' => '1104', 'name' => 'Persediaan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 14, 'parent' => 4, 'code' => '110401', 'name' => 'Persediaan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 14, 'parent' => 4, 'code' => '110402', 'name' => 'Persediaan Terkirim', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 15, 'parent' => NULL, 'code' => '1103', 'name' => 'Piutang Usaha', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 15, 'parent' => 3, 'code' => '110301', 'name' => 'Piutang Usaha IDR', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 15, 'parent' => 3, 'code' => '110302', 'name' => 'Uang Muka Pembelian IDR', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 15, 'parent' => 3, 'code' => '110303', 'name' => 'Piutang Usaha USD', 'currency' => 2, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 15, 'parent' => 3, 'code' => '110304', 'name' => 'Uang Muka Pembelian USD', 'currency' => 2, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 15, 'parent' => 3, 'code' => '110305', 'name' => 'Piutang Karyawan', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
            ['type' => 15, 'parent' => 3, 'code' => '110306', 'name' => 'Piutang Lain-lain', 'currency' => 1, 'initial_balance' => NULL, 'effective_date' => NULL],
        );

        DB::table('account_lists')->insert($data);
    }
}
